logging.level.com.reliaquest: DEBUG
spring.application.name: employee-api
server.port: 8111

server:
  base-url: http://localhost:8112/api/v1/employee

# Resilience4j Configuration
resilience4j.circuitbreaker.instances.server:
  failure-rate-threshold: 50
  wait-duration-in-open-state: 30s
  sliding-window-size: 10
  minimum-number-of-calls: 5